package com.facebook.react.uimanager;

import android.widget.ImageView;
import com.facebook.react.uimanager.events.TouchEventType;
import com.facebook.react.views.textinput.ReactContentSizeChangedEvent;
import com.reactnativecommunity.picker.PickerItemSelectEvent;
import com.reactnativecommunity.webview.events.TopLoadingErrorEvent;
import com.reactnativecommunity.webview.events.TopLoadingFinishEvent;
import com.reactnativecommunity.webview.events.TopLoadingStartEvent;
import com.reactnativecommunity.webview.events.TopMessageEvent;
import java.util.Map;
import kotlin.Metadata;
import kotlin.TuplesKt;
import kotlin.collections.MapsKt;

/* JADX INFO: compiled from: UIManagerModuleConstants.kt */
/* JADX INFO: loaded from: classes2.dex */
@Metadata(d1 = {"\u0000\u0018\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0003\n\u0002\u0010$\n\u0002\u0010\u000e\n\u0002\b\u0003\bÀ\u0002\u0018\u00002\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0002\u0010\u0003R\u001c\u0010\u0004\u001a\u000e\u0012\u0004\u0012\u00020\u0006\u0012\u0004\u0012\u00020\u00010\u00058\u0006X\u0087\u0004¢\u0006\u0002\n\u0000R\u001c\u0010\u0007\u001a\u000e\u0012\u0004\u0012\u00020\u0006\u0012\u0004\u0012\u00020\u00010\u00058\u0006X\u0087\u0004¢\u0006\u0002\n\u0000R\u001c\u0010\b\u001a\u000e\u0012\u0004\u0012\u00020\u0006\u0012\u0004\u0012\u00020\u00010\u00058\u0006X\u0087\u0004¢\u0006\u0002\n\u0000¨\u0006\t"}, d2 = {"Lcom/facebook/react/uimanager/UIManagerModuleConstants;", "", "<init>", "()V", "bubblingEventTypeConstants", "", "", "directEventTypeConstants", "constants", "ReactAndroid_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
public final class UIManagerModuleConstants {
    public static final UIManagerModuleConstants INSTANCE = new UIManagerModuleConstants();
    public static final Map<String, Object> bubblingEventTypeConstants = MapsKt.mapOf(TuplesKt.to("topChange", MapsKt.mapOf(TuplesKt.to("phasedRegistrationNames", MapsKt.mapOf(TuplesKt.to("bubbled", "onChange"), TuplesKt.to("captured", "onChangeCapture"))))), TuplesKt.to(PickerItemSelectEvent.EVENT_NAME, MapsKt.mapOf(TuplesKt.to("phasedRegistrationNames", MapsKt.mapOf(TuplesKt.to("bubbled", "onSelect"), TuplesKt.to("captured", "onSelectCapture"))))), TuplesKt.to(TouchEventType.INSTANCE.getJSEventName(TouchEventType.START), MapsKt.mapOf(TuplesKt.to("phasedRegistrationNames", MapsKt.mapOf(TuplesKt.to("bubbled", "onTouchStart"), TuplesKt.to("captured", "onTouchStartCapture"))))), TuplesKt.to(TouchEventType.INSTANCE.getJSEventName(TouchEventType.MOVE), MapsKt.mapOf(TuplesKt.to("phasedRegistrationNames", MapsKt.mapOf(TuplesKt.to("bubbled", "onTouchMove"), TuplesKt.to("captured", "onTouchMoveCapture"))))), TuplesKt.to(TouchEventType.INSTANCE.getJSEventName(TouchEventType.END), MapsKt.mapOf(TuplesKt.to("phasedRegistrationNames", MapsKt.mapOf(TuplesKt.to("bubbled", "onTouchEnd"), TuplesKt.to("captured", "onTouchEndCapture"))))), TuplesKt.to(TouchEventType.INSTANCE.getJSEventName(TouchEventType.CANCEL), MapsKt.mapOf(TuplesKt.to("phasedRegistrationNames", MapsKt.mapOf(TuplesKt.to("bubbled", "onTouchCancel"), TuplesKt.to("captured", "onTouchCancelCapture"))))));
    public static final Map<String, Object> directEventTypeConstants = MapsKt.mapOf(TuplesKt.to(ReactContentSizeChangedEvent.EVENT_NAME, MapsKt.mapOf(TuplesKt.to("registrationName", "onContentSizeChange"))), TuplesKt.to("topLayout", MapsKt.mapOf(TuplesKt.to("registrationName", "onLayout"))), TuplesKt.to(TopLoadingErrorEvent.EVENT_NAME, MapsKt.mapOf(TuplesKt.to("registrationName", "onLoadingError"))), TuplesKt.to(TopLoadingFinishEvent.EVENT_NAME, MapsKt.mapOf(TuplesKt.to("registrationName", "onLoadingFinish"))), TuplesKt.to(TopLoadingStartEvent.EVENT_NAME, MapsKt.mapOf(TuplesKt.to("registrationName", "onLoadingStart"))), TuplesKt.to("topSelectionChange", MapsKt.mapOf(TuplesKt.to("registrationName", "onSelectionChange"))), TuplesKt.to(TopMessageEvent.EVENT_NAME, MapsKt.mapOf(TuplesKt.to("registrationName", "onMessage"))), TuplesKt.to("topScrollBeginDrag", MapsKt.mapOf(TuplesKt.to("registrationName", "onScrollBeginDrag"))), TuplesKt.to("topScrollEndDrag", MapsKt.mapOf(TuplesKt.to("registrationName", "onScrollEndDrag"))), TuplesKt.to("topScroll", MapsKt.mapOf(TuplesKt.to("registrationName", "onScroll"))), TuplesKt.to("topMomentumScrollBegin", MapsKt.mapOf(TuplesKt.to("registrationName", "onMomentumScrollBegin"))), TuplesKt.to("topMomentumScrollEnd", MapsKt.mapOf(TuplesKt.to("registrationName", "onMomentumScrollEnd"))));
    public static final Map<String, Object> constants = MapsKt.mapOf(TuplesKt.to("UIView", MapsKt.mapOf(TuplesKt.to("ContentMode", MapsKt.mapOf(TuplesKt.to("ScaleAspectFit", Integer.valueOf(ImageView.ScaleType.FIT_CENTER.ordinal())), TuplesKt.to("ScaleAspectFill", Integer.valueOf(ImageView.ScaleType.CENTER_CROP.ordinal())), TuplesKt.to("ScaleAspectCenter", Integer.valueOf(ImageView.ScaleType.CENTER_INSIDE.ordinal())))))), TuplesKt.to("StyleConstants", MapsKt.mapOf(TuplesKt.to("PointerEventsValues", MapsKt.mapOf(TuplesKt.to("none", Integer.valueOf(PointerEvents.NONE.ordinal())), TuplesKt.to("boxNone", Integer.valueOf(PointerEvents.BOX_NONE.ordinal())), TuplesKt.to("boxOnly", Integer.valueOf(PointerEvents.BOX_ONLY.ordinal())), TuplesKt.to("unspecified", Integer.valueOf(PointerEvents.AUTO.ordinal())))))), TuplesKt.to("AccessibilityEventTypes", MapsKt.mapOf(TuplesKt.to("typeWindowStateChanged", 32), TuplesKt.to("typeViewFocused", 8), TuplesKt.to("typeViewClicked", 1))));

    private UIManagerModuleConstants() {
    }
}
